/*
 * $Id$
 * $HeadURL$
 */
package shouter.api.beans;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import shouter.api.dao.AwsConstants;

/**
 * The Comment object bean.
 *
 * @author chuck (charlie.effinger@gmail.com)
 * @version $Revision$ $LastChangedDate$
 */
@DynamoDBTable(tableName = AwsConstants.COMMENT_TABLE)
public class Comment {

    private String id;

    private Long timestamp;

    private String userName;

    protected String message;

    private String shoutId;

    public Comment() { }

    public Comment(String shoutId, String message, String userName) {
        this.userName = userName;
        this.message = message;
        this.shoutId = shoutId;
    }

    @DynamoDBHashKey(attributeName = AwsConstants.ID)
    @DynamoDBAutoGeneratedKey
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    @DynamoDBAttribute(attributeName = AwsConstants.USER_NAME)
    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @DynamoDBAttribute(attributeName = AwsConstants.TIMESTAMP)
    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    @DynamoDBAttribute(attributeName = AwsConstants.MESSAGE)
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @DynamoDBRangeKey(attributeName = AwsConstants.SHOUT_ID)
    public String getShoutId() {
        return shoutId;
    }

    public void setShoutId(String shoutId) {
        this.shoutId = shoutId;
    }

    @Override
    public String toString() {
        return "Shout [id=" + id + ", shoutId=" + shoutId + ", message=" + message + ", timestamp=" + timestamp
                + ", userName=" + userName + "]";
    }
}
